// <auto-generated />
using DonkeyWork.Vault.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DonkeyWork.Vault.Persistence.Migrations
{
    [DbContext(typeof(VaultDbContext))]
    [Migration("20260608120000_AddApiKeyUsername")]
    partial class AddApiKeyUsername
    {
    }
}
