// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: vault.proto

package vaultpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CredentialStore_GetApiKey_FullMethodName           = "/donkeywork.vault.v1.CredentialStore/GetApiKey"
	CredentialStore_DescribeCredential_FullMethodName  = "/donkeywork.vault.v1.CredentialStore/DescribeCredential"
	CredentialStore_GetOAuthAccessToken_FullMethodName = "/donkeywork.vault.v1.CredentialStore/GetOAuthAccessToken"
)

// CredentialStoreClient is the client API for CredentialStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------- credential store (hot path) ----------
type CredentialStoreClient interface {
	GetApiKey(ctx context.Context, in *GetApiKeyRequest, opts ...grpc.CallOption) (*GetApiKeyResponse, error)
	DescribeCredential(ctx context.Context, in *DescribeCredentialRequest, opts ...grpc.CallOption) (*DescribeCredentialResponse, error)
	GetOAuthAccessToken(ctx context.Context, in *GetOAuthAccessTokenRequest, opts ...grpc.CallOption) (*GetOAuthAccessTokenResponse, error)
}

type credentialStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialStoreClient(cc grpc.ClientConnInterface) CredentialStoreClient {
	return &credentialStoreClient{cc}
}

func (c *credentialStoreClient) GetApiKey(ctx context.Context, in *GetApiKeyRequest, opts ...grpc.CallOption) (*GetApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApiKeyResponse)
	err := c.cc.Invoke(ctx, CredentialStore_GetApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialStoreClient) DescribeCredential(ctx context.Context, in *DescribeCredentialRequest, opts ...grpc.CallOption) (*DescribeCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeCredentialResponse)
	err := c.cc.Invoke(ctx, CredentialStore_DescribeCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialStoreClient) GetOAuthAccessToken(ctx context.Context, in *GetOAuthAccessTokenRequest, opts ...grpc.CallOption) (*GetOAuthAccessTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOAuthAccessTokenResponse)
	err := c.cc.Invoke(ctx, CredentialStore_GetOAuthAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialStoreServer is the server API for CredentialStore service.
// All implementations must embed UnimplementedCredentialStoreServer
// for forward compatibility.
//
// ---------- credential store (hot path) ----------
type CredentialStoreServer interface {
	GetApiKey(context.Context, *GetApiKeyRequest) (*GetApiKeyResponse, error)
	DescribeCredential(context.Context, *DescribeCredentialRequest) (*DescribeCredentialResponse, error)
	GetOAuthAccessToken(context.Context, *GetOAuthAccessTokenRequest) (*GetOAuthAccessTokenResponse, error)
	mustEmbedUnimplementedCredentialStoreServer()
}

// UnimplementedCredentialStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredentialStoreServer struct{}

func (UnimplementedCredentialStoreServer) GetApiKey(context.Context, *GetApiKeyRequest) (*GetApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApiKey not implemented")
}
func (UnimplementedCredentialStoreServer) DescribeCredential(context.Context, *DescribeCredentialRequest) (*DescribeCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeCredential not implemented")
}
func (UnimplementedCredentialStoreServer) GetOAuthAccessToken(context.Context, *GetOAuthAccessTokenRequest) (*GetOAuthAccessTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOAuthAccessToken not implemented")
}
func (UnimplementedCredentialStoreServer) mustEmbedUnimplementedCredentialStoreServer() {}
func (UnimplementedCredentialStoreServer) testEmbeddedByValue()                         {}

// UnsafeCredentialStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialStoreServer will
// result in compilation errors.
type UnsafeCredentialStoreServer interface {
	mustEmbedUnimplementedCredentialStoreServer()
}

func RegisterCredentialStoreServer(s grpc.ServiceRegistrar, srv CredentialStoreServer) {
	// If the following call panics, it indicates UnimplementedCredentialStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CredentialStore_ServiceDesc, srv)
}

func _CredentialStore_GetApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialStoreServer).GetApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialStore_GetApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialStoreServer).GetApiKey(ctx, req.(*GetApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialStore_DescribeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialStoreServer).DescribeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialStore_DescribeCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialStoreServer).DescribeCredential(ctx, req.(*DescribeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialStore_GetOAuthAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOAuthAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialStoreServer).GetOAuthAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialStore_GetOAuthAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialStoreServer).GetOAuthAccessToken(ctx, req.(*GetOAuthAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CredentialStore_ServiceDesc is the grpc.ServiceDesc for CredentialStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredentialStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donkeywork.vault.v1.CredentialStore",
	HandlerType: (*CredentialStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApiKey",
			Handler:    _CredentialStore_GetApiKey_Handler,
		},
		{
			MethodName: "DescribeCredential",
			Handler:    _CredentialStore_DescribeCredential_Handler,
		},
		{
			MethodName: "GetOAuthAccessToken",
			Handler:    _CredentialStore_GetOAuthAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}

const (
	OAuthTokens_List_FullMethodName = "/donkeywork.vault.v1.OAuthTokens/List"
)

// OAuthTokensClient is the client API for OAuthTokens service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------- oauth token management ----------
type OAuthTokensClient interface {
	List(ctx context.Context, in *ListOAuthTokensRequest, opts ...grpc.CallOption) (*ListOAuthTokensResponse, error)
}

type oAuthTokensClient struct {
	cc grpc.ClientConnInterface
}

func NewOAuthTokensClient(cc grpc.ClientConnInterface) OAuthTokensClient {
	return &oAuthTokensClient{cc}
}

func (c *oAuthTokensClient) List(ctx context.Context, in *ListOAuthTokensRequest, opts ...grpc.CallOption) (*ListOAuthTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOAuthTokensResponse)
	err := c.cc.Invoke(ctx, OAuthTokens_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuthTokensServer is the server API for OAuthTokens service.
// All implementations must embed UnimplementedOAuthTokensServer
// for forward compatibility.
//
// ---------- oauth token management ----------
type OAuthTokensServer interface {
	List(context.Context, *ListOAuthTokensRequest) (*ListOAuthTokensResponse, error)
	mustEmbedUnimplementedOAuthTokensServer()
}

// UnimplementedOAuthTokensServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOAuthTokensServer struct{}

func (UnimplementedOAuthTokensServer) List(context.Context, *ListOAuthTokensRequest) (*ListOAuthTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedOAuthTokensServer) mustEmbedUnimplementedOAuthTokensServer() {}
func (UnimplementedOAuthTokensServer) testEmbeddedByValue()                     {}

// UnsafeOAuthTokensServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OAuthTokensServer will
// result in compilation errors.
type UnsafeOAuthTokensServer interface {
	mustEmbedUnimplementedOAuthTokensServer()
}

func RegisterOAuthTokensServer(s grpc.ServiceRegistrar, srv OAuthTokensServer) {
	// If the following call panics, it indicates UnimplementedOAuthTokensServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OAuthTokens_ServiceDesc, srv)
}

func _OAuthTokens_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOAuthTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthTokensServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthTokens_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthTokensServer).List(ctx, req.(*ListOAuthTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OAuthTokens_ServiceDesc is the grpc.ServiceDesc for OAuthTokens service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OAuthTokens_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donkeywork.vault.v1.OAuthTokens",
	HandlerType: (*OAuthTokensServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _OAuthTokens_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}

const (
	ApiKeys_List_FullMethodName   = "/donkeywork.vault.v1.ApiKeys/List"
	ApiKeys_Create_FullMethodName = "/donkeywork.vault.v1.ApiKeys/Create"
	ApiKeys_Delete_FullMethodName = "/donkeywork.vault.v1.ApiKeys/Delete"
)

// ApiKeysClient is the client API for ApiKeys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------- api key management (brokered by the Portal) ----------
type ApiKeysClient interface {
	List(ctx context.Context, in *ListApiKeysRequest, opts ...grpc.CallOption) (*ListApiKeysResponse, error)
	Create(ctx context.Context, in *CreateApiKeyRequest, opts ...grpc.CallOption) (*ApiKeyItem, error)
	Delete(ctx context.Context, in *DeleteApiKeyRequest, opts ...grpc.CallOption) (*DeleteApiKeyResponse, error)
}

type apiKeysClient struct {
	cc grpc.ClientConnInterface
}

func NewApiKeysClient(cc grpc.ClientConnInterface) ApiKeysClient {
	return &apiKeysClient{cc}
}

func (c *apiKeysClient) List(ctx context.Context, in *ListApiKeysRequest, opts ...grpc.CallOption) (*ListApiKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApiKeysResponse)
	err := c.cc.Invoke(ctx, ApiKeys_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) Create(ctx context.Context, in *CreateApiKeyRequest, opts ...grpc.CallOption) (*ApiKeyItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiKeyItem)
	err := c.cc.Invoke(ctx, ApiKeys_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) Delete(ctx context.Context, in *DeleteApiKeyRequest, opts ...grpc.CallOption) (*DeleteApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteApiKeyResponse)
	err := c.cc.Invoke(ctx, ApiKeys_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiKeysServer is the server API for ApiKeys service.
// All implementations must embed UnimplementedApiKeysServer
// for forward compatibility.
//
// ---------- api key management (brokered by the Portal) ----------
type ApiKeysServer interface {
	List(context.Context, *ListApiKeysRequest) (*ListApiKeysResponse, error)
	Create(context.Context, *CreateApiKeyRequest) (*ApiKeyItem, error)
	Delete(context.Context, *DeleteApiKeyRequest) (*DeleteApiKeyResponse, error)
	mustEmbedUnimplementedApiKeysServer()
}

// UnimplementedApiKeysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiKeysServer struct{}

func (UnimplementedApiKeysServer) List(context.Context, *ListApiKeysRequest) (*ListApiKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedApiKeysServer) Create(context.Context, *CreateApiKeyRequest) (*ApiKeyItem, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedApiKeysServer) Delete(context.Context, *DeleteApiKeyRequest) (*DeleteApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedApiKeysServer) mustEmbedUnimplementedApiKeysServer() {}
func (UnimplementedApiKeysServer) testEmbeddedByValue()                 {}

// UnsafeApiKeysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiKeysServer will
// result in compilation errors.
type UnsafeApiKeysServer interface {
	mustEmbedUnimplementedApiKeysServer()
}

func RegisterApiKeysServer(s grpc.ServiceRegistrar, srv ApiKeysServer) {
	// If the following call panics, it indicates UnimplementedApiKeysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApiKeys_ServiceDesc, srv)
}

func _ApiKeys_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApiKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).List(ctx, req.(*ListApiKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).Create(ctx, req.(*CreateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).Delete(ctx, req.(*DeleteApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiKeys_ServiceDesc is the grpc.ServiceDesc for ApiKeys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiKeys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donkeywork.vault.v1.ApiKeys",
	HandlerType: (*ApiKeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ApiKeys_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ApiKeys_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ApiKeys_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}

const (
	ApiKeyCatalog_ListProviders_FullMethodName = "/donkeywork.vault.v1.ApiKeyCatalog/ListProviders"
	ApiKeyCatalog_GetProvider_FullMethodName   = "/donkeywork.vault.v1.ApiKeyCatalog/GetProvider"
)

// ApiKeyCatalogClient is the client API for ApiKeyCatalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------- api key provider catalog ----------
type ApiKeyCatalogClient interface {
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
	GetProvider(ctx context.Context, in *GetProviderRequest, opts ...grpc.CallOption) (*ApiKeyProvider, error)
}

type apiKeyCatalogClient struct {
	cc grpc.ClientConnInterface
}

func NewApiKeyCatalogClient(cc grpc.ClientConnInterface) ApiKeyCatalogClient {
	return &apiKeyCatalogClient{cc}
}

func (c *apiKeyCatalogClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, ApiKeyCatalog_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeyCatalogClient) GetProvider(ctx context.Context, in *GetProviderRequest, opts ...grpc.CallOption) (*ApiKeyProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiKeyProvider)
	err := c.cc.Invoke(ctx, ApiKeyCatalog_GetProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiKeyCatalogServer is the server API for ApiKeyCatalog service.
// All implementations must embed UnimplementedApiKeyCatalogServer
// for forward compatibility.
//
// ---------- api key provider catalog ----------
type ApiKeyCatalogServer interface {
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	GetProvider(context.Context, *GetProviderRequest) (*ApiKeyProvider, error)
	mustEmbedUnimplementedApiKeyCatalogServer()
}

// UnimplementedApiKeyCatalogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiKeyCatalogServer struct{}

func (UnimplementedApiKeyCatalogServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedApiKeyCatalogServer) GetProvider(context.Context, *GetProviderRequest) (*ApiKeyProvider, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProvider not implemented")
}
func (UnimplementedApiKeyCatalogServer) mustEmbedUnimplementedApiKeyCatalogServer() {}
func (UnimplementedApiKeyCatalogServer) testEmbeddedByValue()                       {}

// UnsafeApiKeyCatalogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiKeyCatalogServer will
// result in compilation errors.
type UnsafeApiKeyCatalogServer interface {
	mustEmbedUnimplementedApiKeyCatalogServer()
}

func RegisterApiKeyCatalogServer(s grpc.ServiceRegistrar, srv ApiKeyCatalogServer) {
	// If the following call panics, it indicates UnimplementedApiKeyCatalogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApiKeyCatalog_ServiceDesc, srv)
}

func _ApiKeyCatalog_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeyCatalogServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeyCatalog_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeyCatalogServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeyCatalog_GetProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeyCatalogServer).GetProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeyCatalog_GetProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeyCatalogServer).GetProvider(ctx, req.(*GetProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiKeyCatalog_ServiceDesc is the grpc.ServiceDesc for ApiKeyCatalog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiKeyCatalog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donkeywork.vault.v1.ApiKeyCatalog",
	HandlerType: (*ApiKeyCatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProviders",
			Handler:    _ApiKeyCatalog_ListProviders_Handler,
		},
		{
			MethodName: "GetProvider",
			Handler:    _ApiKeyCatalog_GetProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}
