// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: vault.proto

package vaultpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CredentialStore_GetApiKey_FullMethodName           = "/donkeywork.vault.v1.CredentialStore/GetApiKey"
	CredentialStore_DescribeCredential_FullMethodName  = "/donkeywork.vault.v1.CredentialStore/DescribeCredential"
	CredentialStore_GetOAuthAccessToken_FullMethodName = "/donkeywork.vault.v1.CredentialStore/GetOAuthAccessToken"
)

// CredentialStoreClient is the client API for CredentialStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------- credential store (hot path) ----------
type CredentialStoreClient interface {
	GetApiKey(ctx context.Context, in *GetApiKeyRequest, opts ...grpc.CallOption) (*GetApiKeyResponse, error)
	DescribeCredential(ctx context.Context, in *DescribeCredentialRequest, opts ...grpc.CallOption) (*DescribeCredentialResponse, error)
	GetOAuthAccessToken(ctx context.Context, in *GetOAuthAccessTokenRequest, opts ...grpc.CallOption) (*GetOAuthAccessTokenResponse, error)
}

type credentialStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialStoreClient(cc grpc.ClientConnInterface) CredentialStoreClient {
	return &credentialStoreClient{cc}
}

func (c *credentialStoreClient) GetApiKey(ctx context.Context, in *GetApiKeyRequest, opts ...grpc.CallOption) (*GetApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApiKeyResponse)
	err := c.cc.Invoke(ctx, CredentialStore_GetApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialStoreClient) DescribeCredential(ctx context.Context, in *DescribeCredentialRequest, opts ...grpc.CallOption) (*DescribeCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeCredentialResponse)
	err := c.cc.Invoke(ctx, CredentialStore_DescribeCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialStoreClient) GetOAuthAccessToken(ctx context.Context, in *GetOAuthAccessTokenRequest, opts ...grpc.CallOption) (*GetOAuthAccessTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOAuthAccessTokenResponse)
	err := c.cc.Invoke(ctx, CredentialStore_GetOAuthAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialStoreServer is the server API for CredentialStore service.
// All implementations must embed UnimplementedCredentialStoreServer
// for forward compatibility.
//
// ---------- credential store (hot path) ----------
type CredentialStoreServer interface {
	GetApiKey(context.Context, *GetApiKeyRequest) (*GetApiKeyResponse, error)
	DescribeCredential(context.Context, *DescribeCredentialRequest) (*DescribeCredentialResponse, error)
	GetOAuthAccessToken(context.Context, *GetOAuthAccessTokenRequest) (*GetOAuthAccessTokenResponse, error)
	mustEmbedUnimplementedCredentialStoreServer()
}

// UnimplementedCredentialStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredentialStoreServer struct{}

func (UnimplementedCredentialStoreServer) GetApiKey(context.Context, *GetApiKeyRequest) (*GetApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApiKey not implemented")
}
func (UnimplementedCredentialStoreServer) DescribeCredential(context.Context, *DescribeCredentialRequest) (*DescribeCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeCredential not implemented")
}
func (UnimplementedCredentialStoreServer) GetOAuthAccessToken(context.Context, *GetOAuthAccessTokenRequest) (*GetOAuthAccessTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOAuthAccessToken not implemented")
}
func (UnimplementedCredentialStoreServer) mustEmbedUnimplementedCredentialStoreServer() {}
func (UnimplementedCredentialStoreServer) testEmbeddedByValue()                         {}

// UnsafeCredentialStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialStoreServer will
// result in compilation errors.
type UnsafeCredentialStoreServer interface {
	mustEmbedUnimplementedCredentialStoreServer()
}

func RegisterCredentialStoreServer(s grpc.ServiceRegistrar, srv CredentialStoreServer) {
	// If the following call panics, it indicates UnimplementedCredentialStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CredentialStore_ServiceDesc, srv)
}

func _CredentialStore_GetApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialStoreServer).GetApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialStore_GetApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialStoreServer).GetApiKey(ctx, req.(*GetApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialStore_DescribeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialStoreServer).DescribeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialStore_DescribeCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialStoreServer).DescribeCredential(ctx, req.(*DescribeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialStore_GetOAuthAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOAuthAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialStoreServer).GetOAuthAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialStore_GetOAuthAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialStoreServer).GetOAuthAccessToken(ctx, req.(*GetOAuthAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CredentialStore_ServiceDesc is the grpc.ServiceDesc for CredentialStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredentialStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donkeywork.vault.v1.CredentialStore",
	HandlerType: (*CredentialStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApiKey",
			Handler:    _CredentialStore_GetApiKey_Handler,
		},
		{
			MethodName: "DescribeCredential",
			Handler:    _CredentialStore_DescribeCredential_Handler,
		},
		{
			MethodName: "GetOAuthAccessToken",
			Handler:    _CredentialStore_GetOAuthAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}

const (
	OAuthTokens_List_FullMethodName = "/donkeywork.vault.v1.OAuthTokens/List"
)

// OAuthTokensClient is the client API for OAuthTokens service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------- oauth token management ----------
type OAuthTokensClient interface {
	List(ctx context.Context, in *ListOAuthTokensRequest, opts ...grpc.CallOption) (*ListOAuthTokensResponse, error)
}

type oAuthTokensClient struct {
	cc grpc.ClientConnInterface
}

func NewOAuthTokensClient(cc grpc.ClientConnInterface) OAuthTokensClient {
	return &oAuthTokensClient{cc}
}

func (c *oAuthTokensClient) List(ctx context.Context, in *ListOAuthTokensRequest, opts ...grpc.CallOption) (*ListOAuthTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOAuthTokensResponse)
	err := c.cc.Invoke(ctx, OAuthTokens_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuthTokensServer is the server API for OAuthTokens service.
// All implementations must embed UnimplementedOAuthTokensServer
// for forward compatibility.
//
// ---------- oauth token management ----------
type OAuthTokensServer interface {
	List(context.Context, *ListOAuthTokensRequest) (*ListOAuthTokensResponse, error)
	mustEmbedUnimplementedOAuthTokensServer()
}

// UnimplementedOAuthTokensServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOAuthTokensServer struct{}

func (UnimplementedOAuthTokensServer) List(context.Context, *ListOAuthTokensRequest) (*ListOAuthTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedOAuthTokensServer) mustEmbedUnimplementedOAuthTokensServer() {}
func (UnimplementedOAuthTokensServer) testEmbeddedByValue()                     {}

// UnsafeOAuthTokensServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OAuthTokensServer will
// result in compilation errors.
type UnsafeOAuthTokensServer interface {
	mustEmbedUnimplementedOAuthTokensServer()
}

func RegisterOAuthTokensServer(s grpc.ServiceRegistrar, srv OAuthTokensServer) {
	// If the following call panics, it indicates UnimplementedOAuthTokensServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OAuthTokens_ServiceDesc, srv)
}

func _OAuthTokens_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOAuthTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthTokensServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthTokens_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthTokensServer).List(ctx, req.(*ListOAuthTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OAuthTokens_ServiceDesc is the grpc.ServiceDesc for OAuthTokens service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OAuthTokens_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donkeywork.vault.v1.OAuthTokens",
	HandlerType: (*OAuthTokensServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _OAuthTokens_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}

const (
	ApiKeys_List_FullMethodName   = "/donkeywork.vault.v1.ApiKeys/List"
	ApiKeys_Create_FullMethodName = "/donkeywork.vault.v1.ApiKeys/Create"
	ApiKeys_Delete_FullMethodName = "/donkeywork.vault.v1.ApiKeys/Delete"
)

// ApiKeysClient is the client API for ApiKeys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------- api key management (brokered by the Portal) ----------
type ApiKeysClient interface {
	List(ctx context.Context, in *ListApiKeysRequest, opts ...grpc.CallOption) (*ListApiKeysResponse, error)
	Create(ctx context.Context, in *CreateApiKeyRequest, opts ...grpc.CallOption) (*ApiKeyItem, error)
	Delete(ctx context.Context, in *DeleteApiKeyRequest, opts ...grpc.CallOption) (*DeleteApiKeyResponse, error)
}

type apiKeysClient struct {
	cc grpc.ClientConnInterface
}

func NewApiKeysClient(cc grpc.ClientConnInterface) ApiKeysClient {
	return &apiKeysClient{cc}
}

func (c *apiKeysClient) List(ctx context.Context, in *ListApiKeysRequest, opts ...grpc.CallOption) (*ListApiKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApiKeysResponse)
	err := c.cc.Invoke(ctx, ApiKeys_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) Create(ctx context.Context, in *CreateApiKeyRequest, opts ...grpc.CallOption) (*ApiKeyItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiKeyItem)
	err := c.cc.Invoke(ctx, ApiKeys_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) Delete(ctx context.Context, in *DeleteApiKeyRequest, opts ...grpc.CallOption) (*DeleteApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteApiKeyResponse)
	err := c.cc.Invoke(ctx, ApiKeys_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiKeysServer is the server API for ApiKeys service.
// All implementations must embed UnimplementedApiKeysServer
// for forward compatibility.
//
// ---------- api key management (brokered by the Portal) ----------
type ApiKeysServer interface {
	List(context.Context, *ListApiKeysRequest) (*ListApiKeysResponse, error)
	Create(context.Context, *CreateApiKeyRequest) (*ApiKeyItem, error)
	Delete(context.Context, *DeleteApiKeyRequest) (*DeleteApiKeyResponse, error)
	mustEmbedUnimplementedApiKeysServer()
}

// UnimplementedApiKeysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiKeysServer struct{}

func (UnimplementedApiKeysServer) List(context.Context, *ListApiKeysRequest) (*ListApiKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedApiKeysServer) Create(context.Context, *CreateApiKeyRequest) (*ApiKeyItem, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedApiKeysServer) Delete(context.Context, *DeleteApiKeyRequest) (*DeleteApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedApiKeysServer) mustEmbedUnimplementedApiKeysServer() {}
func (UnimplementedApiKeysServer) testEmbeddedByValue()                 {}

// UnsafeApiKeysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiKeysServer will
// result in compilation errors.
type UnsafeApiKeysServer interface {
	mustEmbedUnimplementedApiKeysServer()
}

func RegisterApiKeysServer(s grpc.ServiceRegistrar, srv ApiKeysServer) {
	// If the following call panics, it indicates UnimplementedApiKeysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApiKeys_ServiceDesc, srv)
}

func _ApiKeys_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApiKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).List(ctx, req.(*ListApiKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).Create(ctx, req.(*CreateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).Delete(ctx, req.(*DeleteApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiKeys_ServiceDesc is the grpc.ServiceDesc for ApiKeys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiKeys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donkeywork.vault.v1.ApiKeys",
	HandlerType: (*ApiKeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ApiKeys_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ApiKeys_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ApiKeys_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}

const (
	ApiKeyCatalog_ListProviders_FullMethodName = "/donkeywork.vault.v1.ApiKeyCatalog/ListProviders"
	ApiKeyCatalog_GetProvider_FullMethodName   = "/donkeywork.vault.v1.ApiKeyCatalog/GetProvider"
)

// ApiKeyCatalogClient is the client API for ApiKeyCatalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------- api key provider catalog ----------
type ApiKeyCatalogClient interface {
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
	GetProvider(ctx context.Context, in *GetProviderRequest, opts ...grpc.CallOption) (*ApiKeyProvider, error)
}

type apiKeyCatalogClient struct {
	cc grpc.ClientConnInterface
}

func NewApiKeyCatalogClient(cc grpc.ClientConnInterface) ApiKeyCatalogClient {
	return &apiKeyCatalogClient{cc}
}

func (c *apiKeyCatalogClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, ApiKeyCatalog_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeyCatalogClient) GetProvider(ctx context.Context, in *GetProviderRequest, opts ...grpc.CallOption) (*ApiKeyProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiKeyProvider)
	err := c.cc.Invoke(ctx, ApiKeyCatalog_GetProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiKeyCatalogServer is the server API for ApiKeyCatalog service.
// All implementations must embed UnimplementedApiKeyCatalogServer
// for forward compatibility.
//
// ---------- api key provider catalog ----------
type ApiKeyCatalogServer interface {
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	GetProvider(context.Context, *GetProviderRequest) (*ApiKeyProvider, error)
	mustEmbedUnimplementedApiKeyCatalogServer()
}

// UnimplementedApiKeyCatalogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiKeyCatalogServer struct{}

func (UnimplementedApiKeyCatalogServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedApiKeyCatalogServer) GetProvider(context.Context, *GetProviderRequest) (*ApiKeyProvider, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProvider not implemented")
}
func (UnimplementedApiKeyCatalogServer) mustEmbedUnimplementedApiKeyCatalogServer() {}
func (UnimplementedApiKeyCatalogServer) testEmbeddedByValue()                       {}

// UnsafeApiKeyCatalogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiKeyCatalogServer will
// result in compilation errors.
type UnsafeApiKeyCatalogServer interface {
	mustEmbedUnimplementedApiKeyCatalogServer()
}

func RegisterApiKeyCatalogServer(s grpc.ServiceRegistrar, srv ApiKeyCatalogServer) {
	// If the following call panics, it indicates UnimplementedApiKeyCatalogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApiKeyCatalog_ServiceDesc, srv)
}

func _ApiKeyCatalog_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeyCatalogServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeyCatalog_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeyCatalogServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeyCatalog_GetProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeyCatalogServer).GetProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeyCatalog_GetProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeyCatalogServer).GetProvider(ctx, req.(*GetProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiKeyCatalog_ServiceDesc is the grpc.ServiceDesc for ApiKeyCatalog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiKeyCatalog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donkeywork.vault.v1.ApiKeyCatalog",
	HandlerType: (*ApiKeyCatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProviders",
			Handler:    _ApiKeyCatalog_ListProviders_Handler,
		},
		{
			MethodName: "GetProvider",
			Handler:    _ApiKeyCatalog_GetProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}

const (
	Manifests_ListApiKey_FullMethodName   = "/donkeywork.vault.v1.Manifests/ListApiKey"
	Manifests_UpsertApiKey_FullMethodName = "/donkeywork.vault.v1.Manifests/UpsertApiKey"
	Manifests_ListOAuth_FullMethodName    = "/donkeywork.vault.v1.Manifests/ListOAuth"
	Manifests_UpsertOAuth_FullMethodName  = "/donkeywork.vault.v1.Manifests/UpsertOAuth"
	Manifests_Delete_FullMethodName       = "/donkeywork.vault.v1.Manifests/Delete"
	Manifests_DiscoverOidc_FullMethodName = "/donkeywork.vault.v1.Manifests/DiscoverOidc"
)

// ManifestsClient is the client API for Manifests service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManifestsClient interface {
	ListApiKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListApiKeyManifestsResponse, error)
	UpsertApiKey(ctx context.Context, in *ApiKeyProvider, opts ...grpc.CallOption) (*ApiKeyProvider, error)
	ListOAuth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListOAuthManifestsResponse, error)
	UpsertOAuth(ctx context.Context, in *OAuthManifestMsg, opts ...grpc.CallOption) (*OAuthManifestMsg, error)
	Delete(ctx context.Context, in *DeleteManifestRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	DiscoverOidc(ctx context.Context, in *DiscoverOidcRequest, opts ...grpc.CallOption) (*OAuthManifestMsg, error)
}

type manifestsClient struct {
	cc grpc.ClientConnInterface
}

func NewManifestsClient(cc grpc.ClientConnInterface) ManifestsClient {
	return &manifestsClient{cc}
}

func (c *manifestsClient) ListApiKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListApiKeyManifestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApiKeyManifestsResponse)
	err := c.cc.Invoke(ctx, Manifests_ListApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manifestsClient) UpsertApiKey(ctx context.Context, in *ApiKeyProvider, opts ...grpc.CallOption) (*ApiKeyProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiKeyProvider)
	err := c.cc.Invoke(ctx, Manifests_UpsertApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manifestsClient) ListOAuth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListOAuthManifestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOAuthManifestsResponse)
	err := c.cc.Invoke(ctx, Manifests_ListOAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manifestsClient) UpsertOAuth(ctx context.Context, in *OAuthManifestMsg, opts ...grpc.CallOption) (*OAuthManifestMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuthManifestMsg)
	err := c.cc.Invoke(ctx, Manifests_UpsertOAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manifestsClient) Delete(ctx context.Context, in *DeleteManifestRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, Manifests_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manifestsClient) DiscoverOidc(ctx context.Context, in *DiscoverOidcRequest, opts ...grpc.CallOption) (*OAuthManifestMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuthManifestMsg)
	err := c.cc.Invoke(ctx, Manifests_DiscoverOidc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManifestsServer is the server API for Manifests service.
// All implementations must embed UnimplementedManifestsServer
// for forward compatibility.
type ManifestsServer interface {
	ListApiKey(context.Context, *Empty) (*ListApiKeyManifestsResponse, error)
	UpsertApiKey(context.Context, *ApiKeyProvider) (*ApiKeyProvider, error)
	ListOAuth(context.Context, *Empty) (*ListOAuthManifestsResponse, error)
	UpsertOAuth(context.Context, *OAuthManifestMsg) (*OAuthManifestMsg, error)
	Delete(context.Context, *DeleteManifestRequest) (*DeleteResponse, error)
	DiscoverOidc(context.Context, *DiscoverOidcRequest) (*OAuthManifestMsg, error)
	mustEmbedUnimplementedManifestsServer()
}

// UnimplementedManifestsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManifestsServer struct{}

func (UnimplementedManifestsServer) ListApiKey(context.Context, *Empty) (*ListApiKeyManifestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApiKey not implemented")
}
func (UnimplementedManifestsServer) UpsertApiKey(context.Context, *ApiKeyProvider) (*ApiKeyProvider, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertApiKey not implemented")
}
func (UnimplementedManifestsServer) ListOAuth(context.Context, *Empty) (*ListOAuthManifestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOAuth not implemented")
}
func (UnimplementedManifestsServer) UpsertOAuth(context.Context, *OAuthManifestMsg) (*OAuthManifestMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertOAuth not implemented")
}
func (UnimplementedManifestsServer) Delete(context.Context, *DeleteManifestRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedManifestsServer) DiscoverOidc(context.Context, *DiscoverOidcRequest) (*OAuthManifestMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverOidc not implemented")
}
func (UnimplementedManifestsServer) mustEmbedUnimplementedManifestsServer() {}
func (UnimplementedManifestsServer) testEmbeddedByValue()                   {}

// UnsafeManifestsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManifestsServer will
// result in compilation errors.
type UnsafeManifestsServer interface {
	mustEmbedUnimplementedManifestsServer()
}

func RegisterManifestsServer(s grpc.ServiceRegistrar, srv ManifestsServer) {
	// If the following call panics, it indicates UnimplementedManifestsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Manifests_ServiceDesc, srv)
}

func _Manifests_ListApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestsServer).ListApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manifests_ListApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestsServer).ListApiKey(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manifests_UpsertApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiKeyProvider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestsServer).UpsertApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manifests_UpsertApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestsServer).UpsertApiKey(ctx, req.(*ApiKeyProvider))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manifests_ListOAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestsServer).ListOAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manifests_ListOAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestsServer).ListOAuth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manifests_UpsertOAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OAuthManifestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestsServer).UpsertOAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manifests_UpsertOAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestsServer).UpsertOAuth(ctx, req.(*OAuthManifestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manifests_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manifests_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestsServer).Delete(ctx, req.(*DeleteManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manifests_DiscoverOidc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverOidcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestsServer).DiscoverOidc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manifests_DiscoverOidc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestsServer).DiscoverOidc(ctx, req.(*DiscoverOidcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Manifests_ServiceDesc is the grpc.ServiceDesc for Manifests service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Manifests_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donkeywork.vault.v1.Manifests",
	HandlerType: (*ManifestsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApiKey",
			Handler:    _Manifests_ListApiKey_Handler,
		},
		{
			MethodName: "UpsertApiKey",
			Handler:    _Manifests_UpsertApiKey_Handler,
		},
		{
			MethodName: "ListOAuth",
			Handler:    _Manifests_ListOAuth_Handler,
		},
		{
			MethodName: "UpsertOAuth",
			Handler:    _Manifests_UpsertOAuth_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Manifests_Delete_Handler,
		},
		{
			MethodName: "DiscoverOidc",
			Handler:    _Manifests_DiscoverOidc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}

const (
	OAuthProviderConfigs_List_FullMethodName   = "/donkeywork.vault.v1.OAuthProviderConfigs/List"
	OAuthProviderConfigs_Upsert_FullMethodName = "/donkeywork.vault.v1.OAuthProviderConfigs/Upsert"
	OAuthProviderConfigs_Delete_FullMethodName = "/donkeywork.vault.v1.OAuthProviderConfigs/Delete"
)

// OAuthProviderConfigsClient is the client API for OAuthProviderConfigs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OAuthProviderConfigsClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListOAuthConfigsResponse, error)
	Upsert(ctx context.Context, in *UpsertOAuthConfigRequest, opts ...grpc.CallOption) (*OAuthConfigItem, error)
	Delete(ctx context.Context, in *DeleteByIdRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type oAuthProviderConfigsClient struct {
	cc grpc.ClientConnInterface
}

func NewOAuthProviderConfigsClient(cc grpc.ClientConnInterface) OAuthProviderConfigsClient {
	return &oAuthProviderConfigsClient{cc}
}

func (c *oAuthProviderConfigsClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListOAuthConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOAuthConfigsResponse)
	err := c.cc.Invoke(ctx, OAuthProviderConfigs_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthProviderConfigsClient) Upsert(ctx context.Context, in *UpsertOAuthConfigRequest, opts ...grpc.CallOption) (*OAuthConfigItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuthConfigItem)
	err := c.cc.Invoke(ctx, OAuthProviderConfigs_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthProviderConfigsClient) Delete(ctx context.Context, in *DeleteByIdRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, OAuthProviderConfigs_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuthProviderConfigsServer is the server API for OAuthProviderConfigs service.
// All implementations must embed UnimplementedOAuthProviderConfigsServer
// for forward compatibility.
type OAuthProviderConfigsServer interface {
	List(context.Context, *Empty) (*ListOAuthConfigsResponse, error)
	Upsert(context.Context, *UpsertOAuthConfigRequest) (*OAuthConfigItem, error)
	Delete(context.Context, *DeleteByIdRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedOAuthProviderConfigsServer()
}

// UnimplementedOAuthProviderConfigsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOAuthProviderConfigsServer struct{}

func (UnimplementedOAuthProviderConfigsServer) List(context.Context, *Empty) (*ListOAuthConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedOAuthProviderConfigsServer) Upsert(context.Context, *UpsertOAuthConfigRequest) (*OAuthConfigItem, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedOAuthProviderConfigsServer) Delete(context.Context, *DeleteByIdRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedOAuthProviderConfigsServer) mustEmbedUnimplementedOAuthProviderConfigsServer() {}
func (UnimplementedOAuthProviderConfigsServer) testEmbeddedByValue()                              {}

// UnsafeOAuthProviderConfigsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OAuthProviderConfigsServer will
// result in compilation errors.
type UnsafeOAuthProviderConfigsServer interface {
	mustEmbedUnimplementedOAuthProviderConfigsServer()
}

func RegisterOAuthProviderConfigsServer(s grpc.ServiceRegistrar, srv OAuthProviderConfigsServer) {
	// If the following call panics, it indicates UnimplementedOAuthProviderConfigsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OAuthProviderConfigs_ServiceDesc, srv)
}

func _OAuthProviderConfigs_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthProviderConfigsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthProviderConfigs_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthProviderConfigsServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthProviderConfigs_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertOAuthConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthProviderConfigsServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthProviderConfigs_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthProviderConfigsServer).Upsert(ctx, req.(*UpsertOAuthConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthProviderConfigs_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthProviderConfigsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthProviderConfigs_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthProviderConfigsServer).Delete(ctx, req.(*DeleteByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OAuthProviderConfigs_ServiceDesc is the grpc.ServiceDesc for OAuthProviderConfigs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OAuthProviderConfigs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donkeywork.vault.v1.OAuthProviderConfigs",
	HandlerType: (*OAuthProviderConfigsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _OAuthProviderConfigs_List_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _OAuthProviderConfigs_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _OAuthProviderConfigs_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}

const (
	AccessKeys_List_FullMethodName         = "/donkeywork.vault.v1.AccessKeys/List"
	AccessKeys_Create_FullMethodName       = "/donkeywork.vault.v1.AccessKeys/Create"
	AccessKeys_SetEnabled_FullMethodName   = "/donkeywork.vault.v1.AccessKeys/SetEnabled"
	AccessKeys_Delete_FullMethodName       = "/donkeywork.vault.v1.AccessKeys/Delete"
	AccessKeys_Authenticate_FullMethodName = "/donkeywork.vault.v1.AccessKeys/Authenticate"
)

// AccessKeysClient is the client API for AccessKeys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------- access keys (scoped auth credentials for the CLI/agents + portal) ----------
// An access key authenticates a caller to the vault (x-api-key metadata) and/or the portal
// (Authorization: Bearer / X-Api-Key). It carries scopes (frontend:read|readwrite,
// vault:read|readwrite) and can be enabled/disabled. The secret is shown ONCE on create;
// only a sha256 hash + display prefix are stored.
type AccessKeysClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAccessKeysResponse, error)
	Create(ctx context.Context, in *CreateAccessKeyRequest, opts ...grpc.CallOption) (*CreateAccessKeyResponse, error)
	SetEnabled(ctx context.Context, in *SetAccessKeyEnabledRequest, opts ...grpc.CallOption) (*AccessKeyItem, error)
	Delete(ctx context.Context, in *DeleteByIdRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Authenticate(ctx context.Context, in *AuthenticateApiKeyRequest, opts ...grpc.CallOption) (*AuthenticateApiKeyResponse, error)
}

type accessKeysClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessKeysClient(cc grpc.ClientConnInterface) AccessKeysClient {
	return &accessKeysClient{cc}
}

func (c *accessKeysClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAccessKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccessKeysResponse)
	err := c.cc.Invoke(ctx, AccessKeys_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessKeysClient) Create(ctx context.Context, in *CreateAccessKeyRequest, opts ...grpc.CallOption) (*CreateAccessKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccessKeyResponse)
	err := c.cc.Invoke(ctx, AccessKeys_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessKeysClient) SetEnabled(ctx context.Context, in *SetAccessKeyEnabledRequest, opts ...grpc.CallOption) (*AccessKeyItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessKeyItem)
	err := c.cc.Invoke(ctx, AccessKeys_SetEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessKeysClient) Delete(ctx context.Context, in *DeleteByIdRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, AccessKeys_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessKeysClient) Authenticate(ctx context.Context, in *AuthenticateApiKeyRequest, opts ...grpc.CallOption) (*AuthenticateApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateApiKeyResponse)
	err := c.cc.Invoke(ctx, AccessKeys_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessKeysServer is the server API for AccessKeys service.
// All implementations must embed UnimplementedAccessKeysServer
// for forward compatibility.
//
// ---------- access keys (scoped auth credentials for the CLI/agents + portal) ----------
// An access key authenticates a caller to the vault (x-api-key metadata) and/or the portal
// (Authorization: Bearer / X-Api-Key). It carries scopes (frontend:read|readwrite,
// vault:read|readwrite) and can be enabled/disabled. The secret is shown ONCE on create;
// only a sha256 hash + display prefix are stored.
type AccessKeysServer interface {
	List(context.Context, *Empty) (*ListAccessKeysResponse, error)
	Create(context.Context, *CreateAccessKeyRequest) (*CreateAccessKeyResponse, error)
	SetEnabled(context.Context, *SetAccessKeyEnabledRequest) (*AccessKeyItem, error)
	Delete(context.Context, *DeleteByIdRequest) (*DeleteResponse, error)
	Authenticate(context.Context, *AuthenticateApiKeyRequest) (*AuthenticateApiKeyResponse, error)
	mustEmbedUnimplementedAccessKeysServer()
}

// UnimplementedAccessKeysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessKeysServer struct{}

func (UnimplementedAccessKeysServer) List(context.Context, *Empty) (*ListAccessKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAccessKeysServer) Create(context.Context, *CreateAccessKeyRequest) (*CreateAccessKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAccessKeysServer) SetEnabled(context.Context, *SetAccessKeyEnabledRequest) (*AccessKeyItem, error) {
	return nil, status.Error(codes.Unimplemented, "method SetEnabled not implemented")
}
func (UnimplementedAccessKeysServer) Delete(context.Context, *DeleteByIdRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAccessKeysServer) Authenticate(context.Context, *AuthenticateApiKeyRequest) (*AuthenticateApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedAccessKeysServer) mustEmbedUnimplementedAccessKeysServer() {}
func (UnimplementedAccessKeysServer) testEmbeddedByValue()                    {}

// UnsafeAccessKeysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessKeysServer will
// result in compilation errors.
type UnsafeAccessKeysServer interface {
	mustEmbedUnimplementedAccessKeysServer()
}

func RegisterAccessKeysServer(s grpc.ServiceRegistrar, srv AccessKeysServer) {
	// If the following call panics, it indicates UnimplementedAccessKeysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessKeys_ServiceDesc, srv)
}

func _AccessKeys_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessKeysServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessKeys_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessKeysServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessKeys_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessKeysServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessKeys_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessKeysServer).Create(ctx, req.(*CreateAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessKeys_SetEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAccessKeyEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessKeysServer).SetEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessKeys_SetEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessKeysServer).SetEnabled(ctx, req.(*SetAccessKeyEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessKeys_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessKeysServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessKeys_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessKeysServer).Delete(ctx, req.(*DeleteByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessKeys_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessKeysServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessKeys_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessKeysServer).Authenticate(ctx, req.(*AuthenticateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessKeys_ServiceDesc is the grpc.ServiceDesc for AccessKeys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessKeys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donkeywork.vault.v1.AccessKeys",
	HandlerType: (*AccessKeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AccessKeys_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AccessKeys_Create_Handler,
		},
		{
			MethodName: "SetEnabled",
			Handler:    _AccessKeys_SetEnabled_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AccessKeys_Delete_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _AccessKeys_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}

const (
	OAuthFlow_Begin_FullMethodName    = "/donkeywork.vault.v1.OAuthFlow/Begin"
	OAuthFlow_Complete_FullMethodName = "/donkeywork.vault.v1.OAuthFlow/Complete"
)

// OAuthFlowClient is the client API for OAuthFlow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OAuthFlowClient interface {
	Begin(ctx context.Context, in *BeginAuthRequest, opts ...grpc.CallOption) (*BeginAuthResponse, error)
	Complete(ctx context.Context, in *CompleteAuthRequest, opts ...grpc.CallOption) (*CompleteAuthResponse, error)
}

type oAuthFlowClient struct {
	cc grpc.ClientConnInterface
}

func NewOAuthFlowClient(cc grpc.ClientConnInterface) OAuthFlowClient {
	return &oAuthFlowClient{cc}
}

func (c *oAuthFlowClient) Begin(ctx context.Context, in *BeginAuthRequest, opts ...grpc.CallOption) (*BeginAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginAuthResponse)
	err := c.cc.Invoke(ctx, OAuthFlow_Begin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthFlowClient) Complete(ctx context.Context, in *CompleteAuthRequest, opts ...grpc.CallOption) (*CompleteAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteAuthResponse)
	err := c.cc.Invoke(ctx, OAuthFlow_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuthFlowServer is the server API for OAuthFlow service.
// All implementations must embed UnimplementedOAuthFlowServer
// for forward compatibility.
type OAuthFlowServer interface {
	Begin(context.Context, *BeginAuthRequest) (*BeginAuthResponse, error)
	Complete(context.Context, *CompleteAuthRequest) (*CompleteAuthResponse, error)
	mustEmbedUnimplementedOAuthFlowServer()
}

// UnimplementedOAuthFlowServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOAuthFlowServer struct{}

func (UnimplementedOAuthFlowServer) Begin(context.Context, *BeginAuthRequest) (*BeginAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Begin not implemented")
}
func (UnimplementedOAuthFlowServer) Complete(context.Context, *CompleteAuthRequest) (*CompleteAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedOAuthFlowServer) mustEmbedUnimplementedOAuthFlowServer() {}
func (UnimplementedOAuthFlowServer) testEmbeddedByValue()                   {}

// UnsafeOAuthFlowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OAuthFlowServer will
// result in compilation errors.
type UnsafeOAuthFlowServer interface {
	mustEmbedUnimplementedOAuthFlowServer()
}

func RegisterOAuthFlowServer(s grpc.ServiceRegistrar, srv OAuthFlowServer) {
	// If the following call panics, it indicates UnimplementedOAuthFlowServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OAuthFlow_ServiceDesc, srv)
}

func _OAuthFlow_Begin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthFlowServer).Begin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthFlow_Begin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthFlowServer).Begin(ctx, req.(*BeginAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthFlow_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthFlowServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthFlow_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthFlowServer).Complete(ctx, req.(*CompleteAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OAuthFlow_ServiceDesc is the grpc.ServiceDesc for OAuthFlow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OAuthFlow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "donkeywork.vault.v1.OAuthFlow",
	HandlerType: (*OAuthFlowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Begin",
			Handler:    _OAuthFlow_Begin_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _OAuthFlow_Complete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault.proto",
}
