// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: vault.proto

package vaultpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------- shared ----------
type ApiKeyField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Secret        bool                   `protobuf:"varint,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyField) Reset() {
	*x = ApiKeyField{}
	mi := &file_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyField) ProtoMessage() {}

func (x *ApiKeyField) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyField.ProtoReflect.Descriptor instead.
func (*ApiKeyField) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{0}
}

func (x *ApiKeyField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKeyField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ApiKeyField) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *ApiKeyField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type ApiKeyProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // manifest id, e.g. "grafana"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl       string                 `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	DocsUrl       string                 `protobuf:"bytes,4,opt,name=docs_url,json=docsUrl,proto3" json:"docs_url,omitempty"`
	AuthScheme    string                 `protobuf:"bytes,5,opt,name=auth_scheme,json=authScheme,proto3" json:"auth_scheme,omitempty"` // header | basic
	Header        string                 `protobuf:"bytes,6,opt,name=header,proto3" json:"header,omitempty"`                           // e.g. Authorization, x-api-key
	Prefix        string                 `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`                           // e.g. "Bearer "
	StaticHeaders map[string]string      `protobuf:"bytes,8,rep,name=static_headers,json=staticHeaders,proto3" json:"static_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BaseUrl       string                 `protobuf:"bytes,9,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Fields        []*ApiKeyField         `protobuf:"bytes,10,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyProvider) Reset() {
	*x = ApiKeyProvider{}
	mi := &file_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyProvider) ProtoMessage() {}

func (x *ApiKeyProvider) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyProvider.ProtoReflect.Descriptor instead.
func (*ApiKeyProvider) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{1}
}

func (x *ApiKeyProvider) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ApiKeyProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKeyProvider) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *ApiKeyProvider) GetDocsUrl() string {
	if x != nil {
		return x.DocsUrl
	}
	return ""
}

func (x *ApiKeyProvider) GetAuthScheme() string {
	if x != nil {
		return x.AuthScheme
	}
	return ""
}

func (x *ApiKeyProvider) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *ApiKeyProvider) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ApiKeyProvider) GetStaticHeaders() map[string]string {
	if x != nil {
		return x.StaticHeaders
	}
	return nil
}

func (x *ApiKeyProvider) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ApiKeyProvider) GetFields() []*ApiKeyField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// How a stored credential is presented on the wire (for the CLI `shape` command).
type CredentialShape struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Header        string                 `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	StaticHeaders map[string]string      `protobuf:"bytes,4,rep,name=static_headers,json=staticHeaders,proto3" json:"static_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialShape) Reset() {
	*x = CredentialShape{}
	mi := &file_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialShape) ProtoMessage() {}

func (x *CredentialShape) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialShape.ProtoReflect.Descriptor instead.
func (*CredentialShape) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{2}
}

func (x *CredentialShape) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CredentialShape) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *CredentialShape) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *CredentialShape) GetStaticHeaders() map[string]string {
	if x != nil {
		return x.StaticHeaders
	}
	return nil
}

type GetOAuthAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuthAccessTokenRequest) Reset() {
	*x = GetOAuthAccessTokenRequest{}
	mi := &file_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthAccessTokenRequest) ProtoMessage() {}

func (x *GetOAuthAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*GetOAuthAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{3}
}

func (x *GetOAuthAccessTokenRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetOAuthAccessTokenRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type GetOAuthAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // ISO 8601 or empty
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuthAccessTokenResponse) Reset() {
	*x = GetOAuthAccessTokenResponse{}
	mi := &file_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthAccessTokenResponse) ProtoMessage() {}

func (x *GetOAuthAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*GetOAuthAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{4}
}

func (x *GetOAuthAccessTokenResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetOAuthAccessTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetOAuthAccessTokenResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *GetOAuthAccessTokenResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type ListOAuthTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOAuthTokensRequest) Reset() {
	*x = ListOAuthTokensRequest{}
	mi := &file_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOAuthTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOAuthTokensRequest) ProtoMessage() {}

func (x *ListOAuthTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOAuthTokensRequest.ProtoReflect.Descriptor instead.
func (*ListOAuthTokensRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{5}
}

type OAuthTokenSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider        string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Account         string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	ExpiresAt       string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	LastRefreshedAt string                 `protobuf:"bytes,5,opt,name=last_refreshed_at,json=lastRefreshedAt,proto3" json:"last_refreshed_at,omitempty"`
	Scopes          []string               `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OAuthTokenSummary) Reset() {
	*x = OAuthTokenSummary{}
	mi := &file_vault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthTokenSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthTokenSummary) ProtoMessage() {}

func (x *OAuthTokenSummary) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthTokenSummary.ProtoReflect.Descriptor instead.
func (*OAuthTokenSummary) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{6}
}

func (x *OAuthTokenSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OAuthTokenSummary) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OAuthTokenSummary) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *OAuthTokenSummary) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *OAuthTokenSummary) GetLastRefreshedAt() string {
	if x != nil {
		return x.LastRefreshedAt
	}
	return ""
}

func (x *OAuthTokenSummary) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type ListOAuthTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OAuthTokenSummary   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOAuthTokensResponse) Reset() {
	*x = ListOAuthTokensResponse{}
	mi := &file_vault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOAuthTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOAuthTokensResponse) ProtoMessage() {}

func (x *ListOAuthTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOAuthTokensResponse.ProtoReflect.Descriptor instead.
func (*ListOAuthTokensResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{7}
}

func (x *ListOAuthTokensResponse) GetItems() []*OAuthTokenSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // optional; selects among multiple stored keys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiKeyRequest) Reset() {
	*x = GetApiKeyRequest{}
	mi := &file_vault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiKeyRequest) ProtoMessage() {}

func (x *GetApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiKeyRequest.ProtoReflect.Descriptor instead.
func (*GetApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{8}
}

func (x *GetApiKeyRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetApiKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"` // the primary secret field value
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiKeyResponse) Reset() {
	*x = GetApiKeyResponse{}
	mi := &file_vault_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiKeyResponse) ProtoMessage() {}

func (x *GetApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiKeyResponse.ProtoReflect.Descriptor instead.
func (*GetApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{9}
}

func (x *GetApiKeyResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetApiKeyResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *GetApiKeyResponse) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DescribeCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeCredentialRequest) Reset() {
	*x = DescribeCredentialRequest{}
	mi := &file_vault_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCredentialRequest) ProtoMessage() {}

func (x *DescribeCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCredentialRequest.ProtoReflect.Descriptor instead.
func (*DescribeCredentialRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{10}
}

func (x *DescribeCredentialRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DescribeCredentialRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DescribeCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Shape         *CredentialShape       `protobuf:"bytes,2,opt,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeCredentialResponse) Reset() {
	*x = DescribeCredentialResponse{}
	mi := &file_vault_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCredentialResponse) ProtoMessage() {}

func (x *DescribeCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCredentialResponse.ProtoReflect.Descriptor instead.
func (*DescribeCredentialResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{11}
}

func (x *DescribeCredentialResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *DescribeCredentialResponse) GetShape() *CredentialShape {
	if x != nil {
		return x.Shape
	}
	return nil
}

type ApiKeyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`      // ISO 8601
	LastUsedAt    string                 `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"` // ISO 8601 or empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyItem) Reset() {
	*x = ApiKeyItem{}
	mi := &file_vault_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyItem) ProtoMessage() {}

func (x *ApiKeyItem) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyItem.ProtoReflect.Descriptor instead.
func (*ApiKeyItem) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{12}
}

func (x *ApiKeyItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKeyItem) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ApiKeyItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKeyItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ApiKeyItem) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

type ListApiKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApiKeysRequest) Reset() {
	*x = ListApiKeysRequest{}
	mi := &file_vault_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysRequest) ProtoMessage() {}

func (x *ListApiKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysRequest.ProtoReflect.Descriptor instead.
func (*ListApiKeysRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{13}
}

type ListApiKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ApiKeyItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApiKeysResponse) Reset() {
	*x = ListApiKeysResponse{}
	mi := &file_vault_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysResponse) ProtoMessage() {}

func (x *ListApiKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysResponse.ProtoReflect.Descriptor instead.
func (*ListApiKeysResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{14}
}

func (x *ListApiKeysResponse) GetItems() []*ApiKeyItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // validated against the provider manifest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyRequest) Reset() {
	*x = CreateApiKeyRequest{}
	mi := &file_vault_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyRequest) ProtoMessage() {}

func (x *CreateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{15}
}

func (x *CreateApiKeyRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateApiKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApiKeyRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DeleteApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiKeyRequest) Reset() {
	*x = DeleteApiKeyRequest{}
	mi := &file_vault_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiKeyRequest) ProtoMessage() {}

func (x *DeleteApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteApiKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiKeyResponse) Reset() {
	*x = DeleteApiKeyResponse{}
	mi := &file_vault_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiKeyResponse) ProtoMessage() {}

func (x *DeleteApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteApiKeyResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_vault_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{18}
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ApiKeyProvider      `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_vault_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{19}
}

func (x *ListProvidersResponse) GetProviders() []*ApiKeyProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type GetProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRequest) Reset() {
	*x = GetProviderRequest{}
	mi := &file_vault_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRequest) ProtoMessage() {}

func (x *GetProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRequest.ProtoReflect.Descriptor instead.
func (*GetProviderRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{20}
}

func (x *GetProviderRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_vault_proto protoreflect.FileDescriptor

const file_vault_proto_rawDesc = "" +
	"\n" +
	"\vvault.proto\x12\x13donkeywork.vault.v1\"k\n" +
	"\vApiKeyField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\bR\x06secret\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\"\xb3\x03\n" +
	"\x0eApiKeyProvider\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\x12\x19\n" +
	"\bdocs_url\x18\x04 \x01(\tR\adocsUrl\x12\x1f\n" +
	"\vauth_scheme\x18\x05 \x01(\tR\n" +
	"authScheme\x12\x16\n" +
	"\x06header\x18\x06 \x01(\tR\x06header\x12\x16\n" +
	"\x06prefix\x18\a \x01(\tR\x06prefix\x12]\n" +
	"\x0estatic_headers\x18\b \x03(\v26.donkeywork.vault.v1.ApiKeyProvider.StaticHeadersEntryR\rstaticHeaders\x12\x19\n" +
	"\bbase_url\x18\t \x01(\tR\abaseUrl\x128\n" +
	"\x06fields\x18\n" +
	" \x03(\v2 .donkeywork.vault.v1.ApiKeyFieldR\x06fields\x1a@\n" +
	"\x12StaticHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfe\x01\n" +
	"\x0fCredentialShape\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x16\n" +
	"\x06header\x18\x02 \x01(\tR\x06header\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12^\n" +
	"\x0estatic_headers\x18\x04 \x03(\v27.donkeywork.vault.v1.CredentialShape.StaticHeadersEntryR\rstaticHeaders\x1a@\n" +
	"\x12StaticHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x1aGetOAuthAccessTokenRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\"\x8d\x01\n" +
	"\x1bGetOAuthAccessTokenResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\"\x18\n" +
	"\x16ListOAuthTokensRequest\"\xbc\x01\n" +
	"\x11OAuthTokenSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\x12*\n" +
	"\x11last_refreshed_at\x18\x05 \x01(\tR\x0flastRefreshedAt\x12\x16\n" +
	"\x06scopes\x18\x06 \x03(\tR\x06scopes\"W\n" +
	"\x17ListOAuthTokensResponse\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.donkeywork.vault.v1.OAuthTokenSummaryR\x05items\"B\n" +
	"\x10GetApiKeyRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xc8\x01\n" +
	"\x11GetApiKeyResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12J\n" +
	"\x06fields\x18\x03 \x03(\v22.donkeywork.vault.v1.GetApiKeyResponse.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x19DescribeCredentialRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"n\n" +
	"\x1aDescribeCredentialResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12:\n" +
	"\x05shape\x18\x02 \x01(\v2$.donkeywork.vault.v1.CredentialShapeR\x05shape\"\x8d\x01\n" +
	"\n" +
	"ApiKeyItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12 \n" +
	"\flast_used_at\x18\x05 \x01(\tR\n" +
	"lastUsedAt\"\x14\n" +
	"\x12ListApiKeysRequest\"L\n" +
	"\x13ListApiKeysResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.donkeywork.vault.v1.ApiKeyItemR\x05items\"\xce\x01\n" +
	"\x13CreateApiKeyRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12L\n" +
	"\x06fields\x18\x03 \x03(\v24.donkeywork.vault.v1.CreateApiKeyRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\x13DeleteApiKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteApiKeyResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\x16\n" +
	"\x14ListProvidersRequest\"Z\n" +
	"\x15ListProvidersResponse\x12A\n" +
	"\tproviders\x18\x01 \x03(\v2#.donkeywork.vault.v1.ApiKeyProviderR\tproviders\"&\n" +
	"\x12GetProviderRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key2\xde\x02\n" +
	"\x0fCredentialStore\x12Z\n" +
	"\tGetApiKey\x12%.donkeywork.vault.v1.GetApiKeyRequest\x1a&.donkeywork.vault.v1.GetApiKeyResponse\x12u\n" +
	"\x12DescribeCredential\x12..donkeywork.vault.v1.DescribeCredentialRequest\x1a/.donkeywork.vault.v1.DescribeCredentialResponse\x12x\n" +
	"\x13GetOAuthAccessToken\x12/.donkeywork.vault.v1.GetOAuthAccessTokenRequest\x1a0.donkeywork.vault.v1.GetOAuthAccessTokenResponse2p\n" +
	"\vOAuthTokens\x12a\n" +
	"\x04List\x12+.donkeywork.vault.v1.ListOAuthTokensRequest\x1a,.donkeywork.vault.v1.ListOAuthTokensResponse2\x98\x02\n" +
	"\aApiKeys\x12Y\n" +
	"\x04List\x12'.donkeywork.vault.v1.ListApiKeysRequest\x1a(.donkeywork.vault.v1.ListApiKeysResponse\x12S\n" +
	"\x06Create\x12(.donkeywork.vault.v1.CreateApiKeyRequest\x1a\x1f.donkeywork.vault.v1.ApiKeyItem\x12]\n" +
	"\x06Delete\x12(.donkeywork.vault.v1.DeleteApiKeyRequest\x1a).donkeywork.vault.v1.DeleteApiKeyResponse2\xd4\x01\n" +
	"\rApiKeyCatalog\x12f\n" +
	"\rListProviders\x12).donkeywork.vault.v1.ListProvidersRequest\x1a*.donkeywork.vault.v1.ListProvidersResponse\x12[\n" +
	"\vGetProvider\x12'.donkeywork.vault.v1.GetProviderRequest\x1a#.donkeywork.vault.v1.ApiKeyProviderBGZ)donkeywork.dev/vault-cli/internal/vaultpb\xaa\x02\x19DonkeyWork.Vault.Proto.V1b\x06proto3"

var (
	file_vault_proto_rawDescOnce sync.Once
	file_vault_proto_rawDescData []byte
)

func file_vault_proto_rawDescGZIP() []byte {
	file_vault_proto_rawDescOnce.Do(func() {
		file_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_proto_rawDesc), len(file_vault_proto_rawDesc)))
	})
	return file_vault_proto_rawDescData
}

var file_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_vault_proto_goTypes = []any{
	(*ApiKeyField)(nil),                 // 0: donkeywork.vault.v1.ApiKeyField
	(*ApiKeyProvider)(nil),              // 1: donkeywork.vault.v1.ApiKeyProvider
	(*CredentialShape)(nil),             // 2: donkeywork.vault.v1.CredentialShape
	(*GetOAuthAccessTokenRequest)(nil),  // 3: donkeywork.vault.v1.GetOAuthAccessTokenRequest
	(*GetOAuthAccessTokenResponse)(nil), // 4: donkeywork.vault.v1.GetOAuthAccessTokenResponse
	(*ListOAuthTokensRequest)(nil),      // 5: donkeywork.vault.v1.ListOAuthTokensRequest
	(*OAuthTokenSummary)(nil),           // 6: donkeywork.vault.v1.OAuthTokenSummary
	(*ListOAuthTokensResponse)(nil),     // 7: donkeywork.vault.v1.ListOAuthTokensResponse
	(*GetApiKeyRequest)(nil),            // 8: donkeywork.vault.v1.GetApiKeyRequest
	(*GetApiKeyResponse)(nil),           // 9: donkeywork.vault.v1.GetApiKeyResponse
	(*DescribeCredentialRequest)(nil),   // 10: donkeywork.vault.v1.DescribeCredentialRequest
	(*DescribeCredentialResponse)(nil),  // 11: donkeywork.vault.v1.DescribeCredentialResponse
	(*ApiKeyItem)(nil),                  // 12: donkeywork.vault.v1.ApiKeyItem
	(*ListApiKeysRequest)(nil),          // 13: donkeywork.vault.v1.ListApiKeysRequest
	(*ListApiKeysResponse)(nil),         // 14: donkeywork.vault.v1.ListApiKeysResponse
	(*CreateApiKeyRequest)(nil),         // 15: donkeywork.vault.v1.CreateApiKeyRequest
	(*DeleteApiKeyRequest)(nil),         // 16: donkeywork.vault.v1.DeleteApiKeyRequest
	(*DeleteApiKeyResponse)(nil),        // 17: donkeywork.vault.v1.DeleteApiKeyResponse
	(*ListProvidersRequest)(nil),        // 18: donkeywork.vault.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),       // 19: donkeywork.vault.v1.ListProvidersResponse
	(*GetProviderRequest)(nil),          // 20: donkeywork.vault.v1.GetProviderRequest
	nil,                                 // 21: donkeywork.vault.v1.ApiKeyProvider.StaticHeadersEntry
	nil,                                 // 22: donkeywork.vault.v1.CredentialShape.StaticHeadersEntry
	nil,                                 // 23: donkeywork.vault.v1.GetApiKeyResponse.FieldsEntry
	nil,                                 // 24: donkeywork.vault.v1.CreateApiKeyRequest.FieldsEntry
}
var file_vault_proto_depIdxs = []int32{
	21, // 0: donkeywork.vault.v1.ApiKeyProvider.static_headers:type_name -> donkeywork.vault.v1.ApiKeyProvider.StaticHeadersEntry
	0,  // 1: donkeywork.vault.v1.ApiKeyProvider.fields:type_name -> donkeywork.vault.v1.ApiKeyField
	22, // 2: donkeywork.vault.v1.CredentialShape.static_headers:type_name -> donkeywork.vault.v1.CredentialShape.StaticHeadersEntry
	6,  // 3: donkeywork.vault.v1.ListOAuthTokensResponse.items:type_name -> donkeywork.vault.v1.OAuthTokenSummary
	23, // 4: donkeywork.vault.v1.GetApiKeyResponse.fields:type_name -> donkeywork.vault.v1.GetApiKeyResponse.FieldsEntry
	2,  // 5: donkeywork.vault.v1.DescribeCredentialResponse.shape:type_name -> donkeywork.vault.v1.CredentialShape
	12, // 6: donkeywork.vault.v1.ListApiKeysResponse.items:type_name -> donkeywork.vault.v1.ApiKeyItem
	24, // 7: donkeywork.vault.v1.CreateApiKeyRequest.fields:type_name -> donkeywork.vault.v1.CreateApiKeyRequest.FieldsEntry
	1,  // 8: donkeywork.vault.v1.ListProvidersResponse.providers:type_name -> donkeywork.vault.v1.ApiKeyProvider
	8,  // 9: donkeywork.vault.v1.CredentialStore.GetApiKey:input_type -> donkeywork.vault.v1.GetApiKeyRequest
	10, // 10: donkeywork.vault.v1.CredentialStore.DescribeCredential:input_type -> donkeywork.vault.v1.DescribeCredentialRequest
	3,  // 11: donkeywork.vault.v1.CredentialStore.GetOAuthAccessToken:input_type -> donkeywork.vault.v1.GetOAuthAccessTokenRequest
	5,  // 12: donkeywork.vault.v1.OAuthTokens.List:input_type -> donkeywork.vault.v1.ListOAuthTokensRequest
	13, // 13: donkeywork.vault.v1.ApiKeys.List:input_type -> donkeywork.vault.v1.ListApiKeysRequest
	15, // 14: donkeywork.vault.v1.ApiKeys.Create:input_type -> donkeywork.vault.v1.CreateApiKeyRequest
	16, // 15: donkeywork.vault.v1.ApiKeys.Delete:input_type -> donkeywork.vault.v1.DeleteApiKeyRequest
	18, // 16: donkeywork.vault.v1.ApiKeyCatalog.ListProviders:input_type -> donkeywork.vault.v1.ListProvidersRequest
	20, // 17: donkeywork.vault.v1.ApiKeyCatalog.GetProvider:input_type -> donkeywork.vault.v1.GetProviderRequest
	9,  // 18: donkeywork.vault.v1.CredentialStore.GetApiKey:output_type -> donkeywork.vault.v1.GetApiKeyResponse
	11, // 19: donkeywork.vault.v1.CredentialStore.DescribeCredential:output_type -> donkeywork.vault.v1.DescribeCredentialResponse
	4,  // 20: donkeywork.vault.v1.CredentialStore.GetOAuthAccessToken:output_type -> donkeywork.vault.v1.GetOAuthAccessTokenResponse
	7,  // 21: donkeywork.vault.v1.OAuthTokens.List:output_type -> donkeywork.vault.v1.ListOAuthTokensResponse
	14, // 22: donkeywork.vault.v1.ApiKeys.List:output_type -> donkeywork.vault.v1.ListApiKeysResponse
	12, // 23: donkeywork.vault.v1.ApiKeys.Create:output_type -> donkeywork.vault.v1.ApiKeyItem
	17, // 24: donkeywork.vault.v1.ApiKeys.Delete:output_type -> donkeywork.vault.v1.DeleteApiKeyResponse
	19, // 25: donkeywork.vault.v1.ApiKeyCatalog.ListProviders:output_type -> donkeywork.vault.v1.ListProvidersResponse
	1,  // 26: donkeywork.vault.v1.ApiKeyCatalog.GetProvider:output_type -> donkeywork.vault.v1.ApiKeyProvider
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_vault_proto_init() }
func file_vault_proto_init() {
	if File_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_proto_rawDesc), len(file_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_vault_proto_goTypes,
		DependencyIndexes: file_vault_proto_depIdxs,
		MessageInfos:      file_vault_proto_msgTypes,
	}.Build()
	File_vault_proto = out.File
	file_vault_proto_goTypes = nil
	file_vault_proto_depIdxs = nil
}
