// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: vault.proto

package vaultpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------- shared ----------
type ApiKeyField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Secret        bool                   `protobuf:"varint,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyField) Reset() {
	*x = ApiKeyField{}
	mi := &file_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyField) ProtoMessage() {}

func (x *ApiKeyField) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyField.ProtoReflect.Descriptor instead.
func (*ApiKeyField) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{0}
}

func (x *ApiKeyField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKeyField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ApiKeyField) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *ApiKeyField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type ApiKeyProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // manifest id, e.g. "grafana"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl       string                 `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	DocsUrl       string                 `protobuf:"bytes,4,opt,name=docs_url,json=docsUrl,proto3" json:"docs_url,omitempty"`
	AuthScheme    string                 `protobuf:"bytes,5,opt,name=auth_scheme,json=authScheme,proto3" json:"auth_scheme,omitempty"` // header | basic
	Header        string                 `protobuf:"bytes,6,opt,name=header,proto3" json:"header,omitempty"`                           // e.g. Authorization, x-api-key
	Prefix        string                 `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`                           // e.g. "Bearer "
	StaticHeaders map[string]string      `protobuf:"bytes,8,rep,name=static_headers,json=staticHeaders,proto3" json:"static_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BaseUrl       string                 `protobuf:"bytes,9,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Fields        []*ApiKeyField         `protobuf:"bytes,10,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyProvider) Reset() {
	*x = ApiKeyProvider{}
	mi := &file_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyProvider) ProtoMessage() {}

func (x *ApiKeyProvider) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyProvider.ProtoReflect.Descriptor instead.
func (*ApiKeyProvider) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{1}
}

func (x *ApiKeyProvider) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ApiKeyProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKeyProvider) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *ApiKeyProvider) GetDocsUrl() string {
	if x != nil {
		return x.DocsUrl
	}
	return ""
}

func (x *ApiKeyProvider) GetAuthScheme() string {
	if x != nil {
		return x.AuthScheme
	}
	return ""
}

func (x *ApiKeyProvider) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *ApiKeyProvider) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ApiKeyProvider) GetStaticHeaders() map[string]string {
	if x != nil {
		return x.StaticHeaders
	}
	return nil
}

func (x *ApiKeyProvider) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ApiKeyProvider) GetFields() []*ApiKeyField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// How a stored credential is presented on the wire (for the CLI `shape` command).
type CredentialShape struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Header        string                 `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	StaticHeaders map[string]string      `protobuf:"bytes,4,rep,name=static_headers,json=staticHeaders,proto3" json:"static_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialShape) Reset() {
	*x = CredentialShape{}
	mi := &file_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialShape) ProtoMessage() {}

func (x *CredentialShape) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialShape.ProtoReflect.Descriptor instead.
func (*CredentialShape) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{2}
}

func (x *CredentialShape) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CredentialShape) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *CredentialShape) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *CredentialShape) GetStaticHeaders() map[string]string {
	if x != nil {
		return x.StaticHeaders
	}
	return nil
}

type GetApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // optional; selects among multiple stored keys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiKeyRequest) Reset() {
	*x = GetApiKeyRequest{}
	mi := &file_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiKeyRequest) ProtoMessage() {}

func (x *GetApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiKeyRequest.ProtoReflect.Descriptor instead.
func (*GetApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{3}
}

func (x *GetApiKeyRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetApiKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"` // the primary secret field value
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiKeyResponse) Reset() {
	*x = GetApiKeyResponse{}
	mi := &file_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiKeyResponse) ProtoMessage() {}

func (x *GetApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiKeyResponse.ProtoReflect.Descriptor instead.
func (*GetApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{4}
}

func (x *GetApiKeyResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetApiKeyResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *GetApiKeyResponse) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DescribeCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeCredentialRequest) Reset() {
	*x = DescribeCredentialRequest{}
	mi := &file_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCredentialRequest) ProtoMessage() {}

func (x *DescribeCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCredentialRequest.ProtoReflect.Descriptor instead.
func (*DescribeCredentialRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeCredentialRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DescribeCredentialRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DescribeCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Shape         *CredentialShape       `protobuf:"bytes,2,opt,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeCredentialResponse) Reset() {
	*x = DescribeCredentialResponse{}
	mi := &file_vault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCredentialResponse) ProtoMessage() {}

func (x *DescribeCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCredentialResponse.ProtoReflect.Descriptor instead.
func (*DescribeCredentialResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeCredentialResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *DescribeCredentialResponse) GetShape() *CredentialShape {
	if x != nil {
		return x.Shape
	}
	return nil
}

type ApiKeyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`      // ISO 8601
	LastUsedAt    string                 `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"` // ISO 8601 or empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyItem) Reset() {
	*x = ApiKeyItem{}
	mi := &file_vault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyItem) ProtoMessage() {}

func (x *ApiKeyItem) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyItem.ProtoReflect.Descriptor instead.
func (*ApiKeyItem) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{7}
}

func (x *ApiKeyItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKeyItem) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ApiKeyItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKeyItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ApiKeyItem) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

type ListApiKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApiKeysRequest) Reset() {
	*x = ListApiKeysRequest{}
	mi := &file_vault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysRequest) ProtoMessage() {}

func (x *ListApiKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysRequest.ProtoReflect.Descriptor instead.
func (*ListApiKeysRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{8}
}

type ListApiKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ApiKeyItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApiKeysResponse) Reset() {
	*x = ListApiKeysResponse{}
	mi := &file_vault_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysResponse) ProtoMessage() {}

func (x *ListApiKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysResponse.ProtoReflect.Descriptor instead.
func (*ListApiKeysResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{9}
}

func (x *ListApiKeysResponse) GetItems() []*ApiKeyItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // validated against the provider manifest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyRequest) Reset() {
	*x = CreateApiKeyRequest{}
	mi := &file_vault_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyRequest) ProtoMessage() {}

func (x *CreateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{10}
}

func (x *CreateApiKeyRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateApiKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApiKeyRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DeleteApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiKeyRequest) Reset() {
	*x = DeleteApiKeyRequest{}
	mi := &file_vault_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiKeyRequest) ProtoMessage() {}

func (x *DeleteApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteApiKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApiKeyResponse) Reset() {
	*x = DeleteApiKeyResponse{}
	mi := &file_vault_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApiKeyResponse) ProtoMessage() {}

func (x *DeleteApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApiKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteApiKeyResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_vault_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{13}
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ApiKeyProvider      `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_vault_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{14}
}

func (x *ListProvidersResponse) GetProviders() []*ApiKeyProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type GetProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRequest) Reset() {
	*x = GetProviderRequest{}
	mi := &file_vault_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRequest) ProtoMessage() {}

func (x *GetProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRequest.ProtoReflect.Descriptor instead.
func (*GetProviderRequest) Descriptor() ([]byte, []int) {
	return file_vault_proto_rawDescGZIP(), []int{15}
}

func (x *GetProviderRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_vault_proto protoreflect.FileDescriptor

const file_vault_proto_rawDesc = "" +
	"\n" +
	"\vvault.proto\x12\x13donkeywork.vault.v1\"k\n" +
	"\vApiKeyField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\bR\x06secret\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\"\xb3\x03\n" +
	"\x0eApiKeyProvider\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\x12\x19\n" +
	"\bdocs_url\x18\x04 \x01(\tR\adocsUrl\x12\x1f\n" +
	"\vauth_scheme\x18\x05 \x01(\tR\n" +
	"authScheme\x12\x16\n" +
	"\x06header\x18\x06 \x01(\tR\x06header\x12\x16\n" +
	"\x06prefix\x18\a \x01(\tR\x06prefix\x12]\n" +
	"\x0estatic_headers\x18\b \x03(\v26.donkeywork.vault.v1.ApiKeyProvider.StaticHeadersEntryR\rstaticHeaders\x12\x19\n" +
	"\bbase_url\x18\t \x01(\tR\abaseUrl\x128\n" +
	"\x06fields\x18\n" +
	" \x03(\v2 .donkeywork.vault.v1.ApiKeyFieldR\x06fields\x1a@\n" +
	"\x12StaticHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfe\x01\n" +
	"\x0fCredentialShape\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x16\n" +
	"\x06header\x18\x02 \x01(\tR\x06header\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12^\n" +
	"\x0estatic_headers\x18\x04 \x03(\v27.donkeywork.vault.v1.CredentialShape.StaticHeadersEntryR\rstaticHeaders\x1a@\n" +
	"\x12StaticHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x10GetApiKeyRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xc8\x01\n" +
	"\x11GetApiKeyResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12J\n" +
	"\x06fields\x18\x03 \x03(\v22.donkeywork.vault.v1.GetApiKeyResponse.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x19DescribeCredentialRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"n\n" +
	"\x1aDescribeCredentialResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12:\n" +
	"\x05shape\x18\x02 \x01(\v2$.donkeywork.vault.v1.CredentialShapeR\x05shape\"\x8d\x01\n" +
	"\n" +
	"ApiKeyItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12 \n" +
	"\flast_used_at\x18\x05 \x01(\tR\n" +
	"lastUsedAt\"\x14\n" +
	"\x12ListApiKeysRequest\"L\n" +
	"\x13ListApiKeysResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.donkeywork.vault.v1.ApiKeyItemR\x05items\"\xce\x01\n" +
	"\x13CreateApiKeyRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12L\n" +
	"\x06fields\x18\x03 \x03(\v24.donkeywork.vault.v1.CreateApiKeyRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\x13DeleteApiKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteApiKeyResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\x16\n" +
	"\x14ListProvidersRequest\"Z\n" +
	"\x15ListProvidersResponse\x12A\n" +
	"\tproviders\x18\x01 \x03(\v2#.donkeywork.vault.v1.ApiKeyProviderR\tproviders\"&\n" +
	"\x12GetProviderRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key2\xe4\x01\n" +
	"\x0fCredentialStore\x12Z\n" +
	"\tGetApiKey\x12%.donkeywork.vault.v1.GetApiKeyRequest\x1a&.donkeywork.vault.v1.GetApiKeyResponse\x12u\n" +
	"\x12DescribeCredential\x12..donkeywork.vault.v1.DescribeCredentialRequest\x1a/.donkeywork.vault.v1.DescribeCredentialResponse2\x98\x02\n" +
	"\aApiKeys\x12Y\n" +
	"\x04List\x12'.donkeywork.vault.v1.ListApiKeysRequest\x1a(.donkeywork.vault.v1.ListApiKeysResponse\x12S\n" +
	"\x06Create\x12(.donkeywork.vault.v1.CreateApiKeyRequest\x1a\x1f.donkeywork.vault.v1.ApiKeyItem\x12]\n" +
	"\x06Delete\x12(.donkeywork.vault.v1.DeleteApiKeyRequest\x1a).donkeywork.vault.v1.DeleteApiKeyResponse2\xd4\x01\n" +
	"\rApiKeyCatalog\x12f\n" +
	"\rListProviders\x12).donkeywork.vault.v1.ListProvidersRequest\x1a*.donkeywork.vault.v1.ListProvidersResponse\x12[\n" +
	"\vGetProvider\x12'.donkeywork.vault.v1.GetProviderRequest\x1a#.donkeywork.vault.v1.ApiKeyProviderBGZ)donkeywork.dev/vault-cli/internal/vaultpb\xaa\x02\x19DonkeyWork.Vault.Proto.V1b\x06proto3"

var (
	file_vault_proto_rawDescOnce sync.Once
	file_vault_proto_rawDescData []byte
)

func file_vault_proto_rawDescGZIP() []byte {
	file_vault_proto_rawDescOnce.Do(func() {
		file_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_proto_rawDesc), len(file_vault_proto_rawDesc)))
	})
	return file_vault_proto_rawDescData
}

var file_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_vault_proto_goTypes = []any{
	(*ApiKeyField)(nil),                // 0: donkeywork.vault.v1.ApiKeyField
	(*ApiKeyProvider)(nil),             // 1: donkeywork.vault.v1.ApiKeyProvider
	(*CredentialShape)(nil),            // 2: donkeywork.vault.v1.CredentialShape
	(*GetApiKeyRequest)(nil),           // 3: donkeywork.vault.v1.GetApiKeyRequest
	(*GetApiKeyResponse)(nil),          // 4: donkeywork.vault.v1.GetApiKeyResponse
	(*DescribeCredentialRequest)(nil),  // 5: donkeywork.vault.v1.DescribeCredentialRequest
	(*DescribeCredentialResponse)(nil), // 6: donkeywork.vault.v1.DescribeCredentialResponse
	(*ApiKeyItem)(nil),                 // 7: donkeywork.vault.v1.ApiKeyItem
	(*ListApiKeysRequest)(nil),         // 8: donkeywork.vault.v1.ListApiKeysRequest
	(*ListApiKeysResponse)(nil),        // 9: donkeywork.vault.v1.ListApiKeysResponse
	(*CreateApiKeyRequest)(nil),        // 10: donkeywork.vault.v1.CreateApiKeyRequest
	(*DeleteApiKeyRequest)(nil),        // 11: donkeywork.vault.v1.DeleteApiKeyRequest
	(*DeleteApiKeyResponse)(nil),       // 12: donkeywork.vault.v1.DeleteApiKeyResponse
	(*ListProvidersRequest)(nil),       // 13: donkeywork.vault.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),      // 14: donkeywork.vault.v1.ListProvidersResponse
	(*GetProviderRequest)(nil),         // 15: donkeywork.vault.v1.GetProviderRequest
	nil,                                // 16: donkeywork.vault.v1.ApiKeyProvider.StaticHeadersEntry
	nil,                                // 17: donkeywork.vault.v1.CredentialShape.StaticHeadersEntry
	nil,                                // 18: donkeywork.vault.v1.GetApiKeyResponse.FieldsEntry
	nil,                                // 19: donkeywork.vault.v1.CreateApiKeyRequest.FieldsEntry
}
var file_vault_proto_depIdxs = []int32{
	16, // 0: donkeywork.vault.v1.ApiKeyProvider.static_headers:type_name -> donkeywork.vault.v1.ApiKeyProvider.StaticHeadersEntry
	0,  // 1: donkeywork.vault.v1.ApiKeyProvider.fields:type_name -> donkeywork.vault.v1.ApiKeyField
	17, // 2: donkeywork.vault.v1.CredentialShape.static_headers:type_name -> donkeywork.vault.v1.CredentialShape.StaticHeadersEntry
	18, // 3: donkeywork.vault.v1.GetApiKeyResponse.fields:type_name -> donkeywork.vault.v1.GetApiKeyResponse.FieldsEntry
	2,  // 4: donkeywork.vault.v1.DescribeCredentialResponse.shape:type_name -> donkeywork.vault.v1.CredentialShape
	7,  // 5: donkeywork.vault.v1.ListApiKeysResponse.items:type_name -> donkeywork.vault.v1.ApiKeyItem
	19, // 6: donkeywork.vault.v1.CreateApiKeyRequest.fields:type_name -> donkeywork.vault.v1.CreateApiKeyRequest.FieldsEntry
	1,  // 7: donkeywork.vault.v1.ListProvidersResponse.providers:type_name -> donkeywork.vault.v1.ApiKeyProvider
	3,  // 8: donkeywork.vault.v1.CredentialStore.GetApiKey:input_type -> donkeywork.vault.v1.GetApiKeyRequest
	5,  // 9: donkeywork.vault.v1.CredentialStore.DescribeCredential:input_type -> donkeywork.vault.v1.DescribeCredentialRequest
	8,  // 10: donkeywork.vault.v1.ApiKeys.List:input_type -> donkeywork.vault.v1.ListApiKeysRequest
	10, // 11: donkeywork.vault.v1.ApiKeys.Create:input_type -> donkeywork.vault.v1.CreateApiKeyRequest
	11, // 12: donkeywork.vault.v1.ApiKeys.Delete:input_type -> donkeywork.vault.v1.DeleteApiKeyRequest
	13, // 13: donkeywork.vault.v1.ApiKeyCatalog.ListProviders:input_type -> donkeywork.vault.v1.ListProvidersRequest
	15, // 14: donkeywork.vault.v1.ApiKeyCatalog.GetProvider:input_type -> donkeywork.vault.v1.GetProviderRequest
	4,  // 15: donkeywork.vault.v1.CredentialStore.GetApiKey:output_type -> donkeywork.vault.v1.GetApiKeyResponse
	6,  // 16: donkeywork.vault.v1.CredentialStore.DescribeCredential:output_type -> donkeywork.vault.v1.DescribeCredentialResponse
	9,  // 17: donkeywork.vault.v1.ApiKeys.List:output_type -> donkeywork.vault.v1.ListApiKeysResponse
	7,  // 18: donkeywork.vault.v1.ApiKeys.Create:output_type -> donkeywork.vault.v1.ApiKeyItem
	12, // 19: donkeywork.vault.v1.ApiKeys.Delete:output_type -> donkeywork.vault.v1.DeleteApiKeyResponse
	14, // 20: donkeywork.vault.v1.ApiKeyCatalog.ListProviders:output_type -> donkeywork.vault.v1.ListProvidersResponse
	1,  // 21: donkeywork.vault.v1.ApiKeyCatalog.GetProvider:output_type -> donkeywork.vault.v1.ApiKeyProvider
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_vault_proto_init() }
func file_vault_proto_init() {
	if File_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_proto_rawDesc), len(file_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_vault_proto_goTypes,
		DependencyIndexes: file_vault_proto_depIdxs,
		MessageInfos:      file_vault_proto_msgTypes,
	}.Build()
	File_vault_proto = out.File
	file_vault_proto_goTypes = nil
	file_vault_proto_depIdxs = nil
}
